# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goatoolsgui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goids',
            name='file',
        ),
        migrations.AddField(
            model_name='goids',
            name='sections_file',
            field=models.FileField(null=True, upload_to='tmp/'),
        ),
    ]
