# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goatoolsgui', '0002_auto_20160911_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='goids',
            name='file_out_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='goids',
            name='go_ids',
            field=models.TextField(default='GO:1234567', max_length=40000),
        ),
        migrations.AddField(
            model_name='goids',
            name='xlsx_data',
            field=models.TextField(default=django.utils.timezone.now, max_length=80000),
            preserve_default=False,
        ),
    ]
