# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 20:27
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goatoolsgui', '0003_auto_20160913_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='goids',
            name='json_data',
            field=jsonfield.fields.JSONField(default='default'),
            preserve_default=False,
        ),
    ]
