# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import goatoolsgui.models


class Migration(migrations.Migration):

    dependencies = [
        ('goatoolsgui', '0004_goids_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='goids',
            name='xlsx_file',
            field=models.FileField(null=True, upload_to=goatoolsgui.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='goids',
            name='sections_file',
            field=models.FileField(null=True, upload_to=goatoolsgui.models.user_directory_path),
        ),
    ]
