# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 17:27
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goatoolsgui', '0005_auto_20161101_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='goids',
            name='plot_data',
            field=jsonfield.fields.JSONField(default={'test': ''}),
            preserve_default=False,
        ),
    ]
