# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 20:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goatoolsgui', '0006_goids_plot_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='goids',
            name='sections',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
